version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: go_crud
      POSTGRES_PASSWORD: go_crud
      POSTGRES_DB: go_crud
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network

volumes:
  postgres_data:
    driver: local

networks:
  postgres-network:
    driver: bridge
